name: siaspri-production

services:
    app:
        environment:
            APP_ENV: production
            APP_DEBUG: false
            APP_URL: https://siapri.com
        volumes:
            - ./.env:/var/www/.env
            - storage_data:/var/www/storage

    queue:
        volumes:
            - ./.env:/var/www/.env
            - storage_data:/var/www/storage

    scheduler:
        volumes:
            - ./.env:/var/www/.env
            - storage_data:/var/www/storage

    web:
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./public:/var/www/public:ro
            - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl:ro

    vite:
        profiles:
            - production-dont-use

volumes:
    storage_data:
    postgres_data:
    redis_data:
